---
- name: Install Docker on EC2 Instances
  hosts:
    - 10.100.3.122
    - 10.100.4.152
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

