# Use an official Node.js runtime as a parent image
FROM node:alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install

RUN build

# Make port 8080 available to the world outside this container
# Define the command to run the application
CMD ["npm", "start"]

